version: "3"

services:
    minecraft-server:
        build: #fdfdfdfdfd
         context: .
         args:
             RAM_AMOUNT: ${RAM_AMOUNT}
        volumes:
          - .server-data:/server
        ports:
          - 25565:25565

        

        container_name:  ${CONTAINER_NAME}        
                
volumes:
   server-data:
  
            
        